### ISSUE TITLE
Unable to add my WAI package through yarn

### ISSUE THREAD

**Issue by Mohit0928** [wasmerio/wasmer-pack#108]
I created a `wasm` file to play with the `wai`. I published it on the [wapm.io](wapm.io). You can find it [here](https://wapm.io/Mohit/tutorial-01). Now, when I'm trying to add it into my React Project. I'm running into this  error when I ran `wasmer add --yarn Mohit/tutorial-01`:
``` 
An unexpected error occurred: "https://registry-cdn.wapm.io/bindings/generator-wasmer/wasmer-pack-cli%400.5.3%3Awasmer-pack/js/Mohit/tutorial-01/tutorial-01-0.1.0.tar.gz: invalid code lengths set".
```
I'm also attaching `yarn-error.log` file which can give a better understanding of the problem.
[yarn-error.log](https://github.com/wasmerio/wai/files/10151407/yarn-error.log)

Let me know if anything else is required from my side.

**Comment by ayys** [comment]
@Mohit0928 Thanks for creating this issue. The bug fixed in prod a few days ago, but older packages were still being affected. I've applied the fix retrospectively, so `wasmer add --yarn Mohit/tutorial-01` should work now.

**Comment by Mohit0928** [comment]
@ayys, I tested it with both `yarn` and `pip`. I'm not getting this error anymore. Thanks @Michael-F-Bryan @ayys 
I'm closing the issue
