### ISSUE TITLE
WASI Support

### ISSUE THREAD

**Issue by eliabieri** [wasmerio/wasmer-pack#126]
Does wasmer-pack support WASI?
Basically, I would like to walk through the [introduction blog post](https://wasmer.io/posts/wasmer-takes-webassembly-libraries-manistream-with-wai), create a package that makes use of WASI, publish it and then consume it using embedded WASMER in Rust.

**Comment by Michael-F-Bryan** [comment]
Yep, it sure does. 

There are even [tests for calling WABT ](https://github.com/wasmerio/wasmer-pack/tree/master/crates/wasmer-pack/tests)(a bunch of CLI tools for working with WebAssembly) from JavaScript and Python.
